apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-rag-pipeline
spec:
  schedule: "*/10 * * * *"   # every 10 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pipeline
            image: newsragacr123.azurecr.io/news-rag-pipeline:latest
            imagePullPolicy: Always

            env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: news-rag-secret
                  key: GOOGLE_API_KEY

            - name: AZURE_SEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: news-rag-secret
                  key: AZURE_SEARCH_KEY

            - name: AZURE_SEARCH_ENDPOINT
              value: "https://news-rag-search-123.search.windows.net"

          restartPolicy: OnFailure